// Generated by CoffeeScript 1.9.0
(function() {
  $(function() {
    var Tic, playerData;
    Tic = {
      data: {
        turns: 0,
        x: {},
        o: {},
        gameOver: false
      },
      assignRoles: function() {
        var player1, player2, randomRole, randomRole2, roles;
        roles = ["X", "O"];
        randomRole = roles[Math.floor(Math.random() * roles.length)];
        if (randomRole === "X") {
          randomRole2 = "O";
        } else {
          randomRole2 = "X";
        }
        playerData.rolep1 = {};
        playerData.rolep2 = {};
        playerData.rolep1[randomRole] = true;
        playerData.rolep2[randomRole2] = true;
        player1 = "<p>" + playerData.player1 + " is playing " + randomRole + " </p>";
        player2 = "<p> " + playerData.player2 + " is playing " + randomRole2 + " </p>";
        return $("#messages").html("").append("<p>X starts first!</p>").append(player1).append(player2).append("<p>" + playerData.player1 + " has " + playerData.p1stats.wins + " wins and " + playerData.p1stats.loses + " loses</p>").append("<p>" + playerData.player2 + " has " + playerData.p2stats.wins + " wins and " + playerData.p2stats.loses + " loses</p>").show('slow');
      },
      initialize: function() {
        var tic, _i;
        $("form").hide('slow');
        $("#tic").html("");
        $(".alerts").hide(900);
        this.data.gameOver = false;
        for (tic = _i = 0; _i <= 8; tic = ++_i) {
          $("<div class='tic'>").appendTo("#tic");
        }
        this.addListeners();
        return this.assignRoles();
      },
      addToScore: function(winningParty) {
        this.data = {
          turns: 0,
          x: {},
          o: {},
          gameOver: true
        };
        $("#messages").html("");
        if (winningParty === "none") {
          this.addAlert("The game was a tie.");
          $("#messages").html("<a href='JavaScript:void(0)' class='play-again'>Play Again?</a>");
          return false;
        }
        if (playerData.rolep1[winningParty] != null) {
          ++playerData.p1stats.wins;
        } else {
          ++playerData.p1stats.loses;
        }
        if (playerData.rolep2[winningParty] != null) {
          ++playerData.p2stats.wins;
        } else {
          ++playerData.p2stats.loses;
        }
        localStorage[playerData.player1] = JSON.stringify(playerData.p1stats);
        localStorage[playerData.player2] = JSON.stringify(playerData.p2stats);
        return $("#messages").html("<a href='JavaScript:void(0)' class='play-again'>Play Again?</a>");
      },
      checkWin: function() {
        var key, value, _ref, _ref1, _results;
        _ref = this.data.x;
        for (key in _ref) {
          value = _ref[key];
          if (value >= 3) {
            localStorage.x++;
            this.addAlert("X wins");
            this.data.gameOver = true;
            this.addToScore("X");
          }
        }
        _ref1 = this.data.o;
        _results = [];
        for (key in _ref1) {
          value = _ref1[key];
          if (value >= 3) {
            localStorage.o++;
            this.addAlert("O wins");
            this.data.gameOver = true;
            _results.push(this.addToScore("O"));
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      },
      checkEnd: function() {
        var col, column, diagonal, diagonals, end, middle, row, start, _i, _j, _k, _l, _len, _len1, _results;
        this.data.x = {};
        this.data.o = {};
        diagonals = [[0, 4, 8], [2, 4, 6]];
        for (_i = 0, _len = diagonals.length; _i < _len; _i++) {
          diagonal = diagonals[_i];
          for (_j = 0, _len1 = diagonal.length; _j < _len1; _j++) {
            col = diagonal[_j];
            this.checkField(col, 'diagonal');
          }
          this.checkWin();
          this.emptyStorageVar('diagonal');
        }
        _results = [];
        for (row = _k = 0; _k <= 2; row = ++_k) {
          start = row * 3;
          end = (row * 3) + 2;
          middle = (row * 3) + 1;
          this.checkField(start, 'start');
          this.checkField(middle, 'middle');
          this.checkField(end, 'end');
          this.checkWin();
          for (column = _l = start; start <= end ? _l <= end : _l >= end; column = start <= end ? ++_l : --_l) {
            this.checkField(column, 'horizontal');
          }
          this.checkWin();
          _results.push(this.emptyStorageVar('horizontal'));
        }
        return _results;
      },
      emptyStorageVar: function(storageVar) {
        this.data.x[storageVar] = null;
        return this.data.o[storageVar] = null;
      },
      checkField: function(field, storageVar) {
        if ($(".tic").eq(field).hasClass("x")) {
          if (this.data.x[storageVar] != null) {
            return this.data.x[storageVar]++;
          } else {
            return this.data.x[storageVar] = 1;
          }
        } else if ($(".tic").eq(field).hasClass("o")) {
          if (this.data.o[storageVar] != null) {
            return this.data.o[storageVar]++;
          } else {
            return this.data.o[storageVar] = 1;
          }
        }
      },
      addListeners: function() {
        return $(".tic").click(function() {
          if (Tic.data.gameOver === false && !$(this).text().length) {
            if (Tic.data.turns % 2 === 0) {
              $(this).html("X").addClass("x moved");
            } else if (Tic.data.turns % 2 !== 0) {
              $(this).html("O").addClass("o moved");
            }
            Tic.data.turns++;
            Tic.checkEnd();
            if (Tic.data.gameOver !== true && $(".moved").length >= 9) {
              return Tic.addToScore("none");
            }
          }
        });
      },
      addAlert: function(msg) {
        $("p.gameAlert").fadeOut('slow').remove();
        $(".alerts").append("<p class='gameAlert'> " + msg + " </p>");
        $(".alerts").show("slow");
        return $("body").animate({
          scrollTop: $(".alerts").offset().top
        }, 'slow');
      }
    };
    playerData = {};
    $("form").on("submit", function(evt) {
      evt.preventDefault();
      playerData.player1 = $("input[name='pl-1']").val();
      playerData.player2 = $("input[name='pl-2']").val();
      if (!playerData.player1 || !playerData.player2) {
        return Tic.addAlert("Player names cannot be empty");
      }
      playerData.p1stats = localStorage[playerData.player1] || {
        wins: 0,
        loses: 0
      };
      if (typeof playerData.p1stats === "string") {
        playerData.p1stats = JSON.parse(playerData.p1stats);
      }
      playerData.p2stats = localStorage[playerData.player2] || {
        wins: 0,
        loses: 0
      };
      if (typeof playerData.p2stats === "string") {
        playerData.p2stats = JSON.parse(playerData.p2stats);
      }
      return Tic.initialize();
    });
    $(".close").click(function() {
      return $(this).parents(".alerts").hide('slow');
    });
    return $("body").on("click", ".play-again", function() {
      return Tic.initialize();
    });
  });

}).call(this);
